spring.application.name=autovista-backend

spring.datasource.url=jdbc:mysql://localhost:3306/autovista?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ankit@04103#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080